name: record_web
description: Web specific implementation for record package called by record_platform_interface.
version: 0.3.1
homepage: https://github.com/llfbandit/record/tree/master/record_web

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  record_platform_interface: 
    path: '../record_platform_interface/'

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      web:
        pluginClass: RecordPluginWeb
        fileName: 'record_web.dart'
