name: record_macos
description: macOS specific implementation for record package called by record_platform_interface.
version: 0.1.0
homepage: https://github.com/llfbandit/record/tree/master/record_macos

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: 
    path: '../record_platform_interface/'

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: RecordMacosPlugin
